[package]
name = "hello_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.17.0", features = ["macros"] }
tokio = { version = "1.28.0", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15.0"
